services:
  web:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./:/var/www/html/ 
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - camagru-network
    ports:
      - "8080:80"

  php:
    container_name: php_container
    build:
      context: ./config/php
    volumes:
      - ./:/var/www/html
    environment:
      DB_HOST: mariadb
      DB_ROOT_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - camagru-network

  mariadb:
    container_name: mariadb_container
    build:
      context: ./config/mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - camagru-network

volumes:
  db-data:

networks:
  camagru-network:
    driver: bridge
